In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\USER\OneDrive\Documents\anaconda_projects\db\shoes_sales_dataset.csv")

In [3]:
#view of the first 5 rows.
df.head()

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD
0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60
1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64
2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08
3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70
4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48

In [4]:
#checking the  health of my dataset to know if there are any missing values or figures

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sale_ID        1000 non-null   object
 1   Date           1000 non-null   object
 2   Brand          1000 non-null   object
 3   Shoe_Type      1000 non-null   object
 4   Color          1000 non-null   object
 5   Country        1000 non-null   object
 6   Sales_Channel  1000 non-null   object
 7   Price_USD      1000 non-null   float64
 8   Units_Sold     1000 non-null   int64
 9   Revenue_USD    1000 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 78.3+ KB

In [5]:
# gives me the count,mean, standard deviation, minimum & maximum ,percentage of my dataset.

df.describe()

         Price_USD   Units_Sold  Revenue_USD
count  1000.000000  1000.000000   1000.00000
mean    137.856420    10.584000   1453.18603
std      64.270059     5.842181   1112.32648
min      31.020000     1.000000     32.38000
25%      81.915000     6.000000    561.05000
50%     139.295000    10.000000   1132.62500
75%     193.752500    16.000000   2163.35000
max     249.940000    20.000000   4938.40000

In [6]:
# change my date from text to what Python can actually understand

df['Date'] = pd.to_datetime(df['Date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sale_ID        1000 non-null   object
 1   Date           1000 non-null   datetime64[ns]
 2   Brand          1000 non-null   object
 3   Shoe_Type      1000 non-null   object
 4   Color          1000 non-null   object
 5   Country        1000 non-null   object
 6   Sales_Channel  1000 non-null   object
 7   Price_USD      1000 non-null   float64
 8   Units_Sold     1000 non-null   int64
 9   Revenue_USD    1000 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 78.3+ KB

In [8]:
#Last 5 rows of my shoes sales dataset.

df.tail()

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD
995,S996,2025-06-06,Puma,Sneakers,Red,India,Online,50.15,6,300.90
996,S997,2025-08-14,Adidas,Casual,Green,France,Online,231.81,2,463.62
997,S998,2025-02-13,Skechers,Running,White,India,Online,60.10,4,240.40
998,S999,2025-05-28,Puma,Boots,Black,France,Retail Store,239.05,1,239.05
999,S1000,2025-08-30,Puma,Casual,Green,India,Online,128.12,1,128.12

In [9]:
# I want to Check Sales by Brand

Brand_performance = df.groupby('Brand')['Revenue_USD'].sum().sort_values().reset_index()

In [10]:
Brand_performance

         Brand  Revenue_USD
0         Nike    192770.15
1         Puma    233749.59
2       Reebok    238826.94
3       Adidas    257039.04
4  New Balance    261631.68
5     Skechers    269168.63

In [11]:
#Average Units per sales

Brand_avg_units = df.groupby('Brand')['Units_Sold'].mean()

In [12]:
Brand_avg_units

Brand
Adidas         11.230303
New Balance    11.300613
Nike           10.215278
Puma           10.341317
Reebok         10.303030
Skechers       10.158163
Name: Units_Sold, dtype: float64

In [13]:
# Sum total revenue by country

Country_sales = df.groupby('Country')['Revenue_USD'].sum().sort_values(ascending=False)

In [14]:
Country_sales

Country
UAE             239807.55
USA             230549.94
France          228079.04
Germany         199667.31
Saudi Arabia    190489.82
UK              186632.61
India           177959.76
Name: Revenue_USD, dtype: float64

In [15]:
# sum total by color

Color_sales = df.groupby('Color')['Units_Sold'].sum().sort_values(ascending=False)

In [16]:
Color_sales

Color
Blue     1923
Grey     1896
Black    1785
Green    1768
Red      1718
White    1494
Name: Units_Sold, dtype: int64

In [17]:
# How to insert data (This means adding a new row and a new column.
# How to insert a new column 
# I inserted 'A TAX COLUMN' At the end

df['Tax_Amount'] = df['Revenue_USD'] * 0.075

In [18]:
df.head()

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD,Tax_Amount
0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60,33.7200
1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64,71.7480
2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08,28.6560
3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70,12.1275
4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48,67.5360

In [19]:
# How to Insert a column in a specific position

df['Tax_Amount'] = df['Price_USD'] * 0.075

In [22]:
df.head()

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD,Tax_Amount
0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60,8.4300
1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64,17.9370
2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08,14.3280
3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70,12.1275
4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48,4.8240

In [25]:
Price_series = df['Price_USD']
print(Price_series)

0      112.40
1      239.16
2      191.04
3      161.70
4       64.32
        ...
995     50.15
996    231.81
997     60.10
998    239.05
999    128.12
Name: Price_USD, Length: 1000, dtype: float64

In [29]:
pd.Series()

Series([], dtype: object)

In [31]:
Price_series = pd.Series('Price_USD')

In [38]:
# practicing the slicing and indexing method
pd.core.series.Series

pandas.core.series.Series

In [45]:
df = pd.read_csv(r"C:\Users\USER\OneDrive\Documents\anaconda_projects\db\shoes_sales_dataset.csv")

In [48]:
price_series = df["Price_USD"]
country_series = df["Country"]
brand_series = df["Brand"]

In [49]:
print(price_series.head())
print(price_series.shape)
print(price_series.dtype)

0    112.40
1    239.16
2    191.04
3    161.70
4     64.32
Name: Price_USD, dtype: float64
(1000,)
float64

In [50]:
price_series.mean()

np.float64(137.85641999999999)

In [51]:
price_series.max()

249.94

In [55]:
Shoe_Type = df[price_series > 300]
print(Shoe_Type)

Empty DataFrame
Columns: [Sale_ID, Date, Brand, Shoe_Type, Color, Country, Sales_Channel, Price_USD, Units_Sold, Revenue_USD]
Index: []

In [57]:
df.reset_index()

,index,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD
0,0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60
1,1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64
2,2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08
3,3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70
4,4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48
...,...,...,...,...,...,...,...,...,...,...,...
995,995,S996,2025-06-06,Puma,Sneakers,Red,India,Online,50.15,6,300.90
996,996,S997,2025-08-14,Adidas,Casual,Green,France,Online,231.81,2,463.62
997,997,S998,2025-02-13,Skechers,Running,White,India,Online,60.10,4,240.40
998,998,S999,2025-05-28,Puma,Boots,Black,France,Retail Store,239.05,1,239.05
999,999,S1000,2025-08-30,Puma,Casual,Green,India,Online,128.12,1,128.12

In [61]:
# Inplace - you want your change to be permanent
df_with_reset = df.reset_in()

In [65]:
df_with_reset.set_index('index')

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD
index,,,,,,,,,,
0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60
1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64
2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08
3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70
4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48
...,...,...,...,...,...,...,...,...,...,...
995,S996,2025-06-06,Puma,Sneakers,Red,India,Online,50.15,6,300.90
996,S997,2025-08-14,Adidas,Casual,Green,France,Online,231.81,2,463.62
997,S998,2025-02-13,Skechers,Running,White,India,Online,60.10,4,240.40
998,S999,2025-05-28,Puma,Boots,Black,France,Retail Store,239.05,1,239.05
999,S1000,2025-08-30,Puma,Casual,Green,India,Online,128.12,1,128.12

In [67]:
#iloc use index strictly but loc allows you call the columns and rows by their actual names

df_with_reset.loc[0:5, 'Brand':'Units_Sold']

         Brand Shoe_Type  Color Country Sales_Channel  Price_USD  Units_Sold
0         Nike     Boots   Blue      UK        Online     112.40           4
1     Skechers     Boots   Grey     USA          Mall     239.16           4
2         Nike   Running  White      UK          Mall     191.04           2
3  New Balance    Casual  Green     UAE          Mall     161.70           1
4       Adidas    Formal   Grey  France        Online      64.32          14
5         Puma    Sports  White      UK  Retail Store      64.32          14